config/routes.rb
Rails.application.routes.draw do

resources :top
resources :users
resources :rooms do
  collection do
    get :back_room
end
end


root 'users#index'
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :rooms
  has_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :group
  has_many :users
end

app/models/room_image.rb
class RoomImage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :room
  validates_presence_of :nickname

 # validate :add_error_sample
 # 「バリデーションチェックをする時は、add_error_sampleメソッドを参照してね」
  def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if nickname.blank?
      puts "エラー"
    end

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :back_room]
  after_action :exec_room_count, only: [:show, :back_room]

  def new
    @room = Room.new
    @room_images = RoomImage.all
    @user = User.find(params[:format])
  end

  def show
    @room = Room.find(params[:id])
    @user.room_id = @room.id
    @user.save
  end

  def back_room
    @room = Room.find(params[:room_id])
    @user.room_id = 0
    @user.save
    @rooms = Room.all
    render :template => "users/show"
  end

  def create
    room = Room.new(create_params)
    if room.save
      user_id = params[:room][:user_id]
      redirect_to :action => "show", :id => "#{room.id}",:user_id =>"#{user_id}"
    end
  end

private

  def create_params
    params.require(:room).permit(:name, :room_image).merge(user_count: 0)
  end

  def set_room
    @user = User.find(params[:user_id])
  end

  def exec_room_count
    case action_name
    when "show" then
      @room.update(user_count: @room.user_count += 1)
    when "bacdk_room" then
      @room.update(user_count: @room.user_count -= 1)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    @images = Image.all
  end

  def create
    user = User.create(nickname: params[:user][:nickname], image: params[:user][:image])
    redirect_to action: 'show', id: "#{user.id}"
  end

  def show
    @user = User.find(params[:id])
    @rooms = Room.order('created_at DESC')
  end

  def create_params
  end

end

app/controllers/websocket_chat_controller.rb
class WebsocketChatController < WebsocketRails::BaseController
    def message_recieve
    # クライアントからのメッセージを取得
    recieve_message = message()
    group_id =recieve_message[1]
   # user_image = User.find(message[2])
    # recieve_message << user_image
    user_image = User.find(message[2]).image
    user_nickname = User.find(message[2]).nickname
    recieve_message << user_image
    recieve_message << user_nickname
    WebsocketRails[group_id].trigger('websocket_chat', recieve_message);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chattest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


    <header class="header">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-1"></div>
        <h1 class="col-sm-4"><a href="/">らくちゃ</a></h1>
        <div class="col-sm-4"></div>
          <% unless @user.nickname.blank? %>
            <div class="col-sm-2">
            <br>
            <%= image_tag(@user.image, class: "top-thumbnail") %>
              <span><%= @user.nickname %></span><br>
              <span><%= link_to "部屋を作る", new_room_path(@user.id) %></span>
            </div>

          <% else %>
            </div>
          <% end %>
          <div class="col-sm-1"></div>
      </div>
    </div>
    </header>


<%= yield %>


</body>
</html>

app/views/rooms/create.js.erb
$('#maked_room').append('<a href="/rooms/<%= @room.id %>"><%= @room.name %></a>')

app/views/rooms/new.html.erb
<div class="container profile top">
  <center><h2>部屋の作成</h2></center>
    <%= form_for(@room) do |f| %>
    <center><%= f.label :room %></center>
    <center> <%= f.text_field :name, placeholder: "部屋の名前",  autofocus: true, class: "nickname" %></center>
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-4">
        <img id="new_room_image">
      </div>
      <div class="col-sm-4">
        部屋の画像をお選びください
        <br>
        <% @room_images.each do |room| %>
          <%= image_tag(room.image, class: "room_thumbnail") %>
        <% end %>
      </div>
      </div class="col-sm-2"><div>
  </div>
</div>
<%= f.hidden_field :room_image %>
<%= f.hidden_field :user_id, :value => "#{@user.id}" %>
  <div><center><%= f.submit value: "部屋作成" %></center></div>
<% end %>

app/views/rooms/show.html.erb
<div class="top", id="top">
  <div class="container">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <div class="form-group">
    <label for="introduction" class="control-label"><%= @room.name %></label>
      <textarea id="comment" cols="45" rows="4"
        placeholder="チャットしましょう" class="form-control"></textarea>
    </div>
    <div class="col-sm-2"></div>

  <button id="send" type="submit" class="btn btn-primary btn-lg">送信</button>
  <%= link_to '退出する', controller: "rooms", action: "back_room", room_id: "#{@room.id}", user_id: "#{@user.id}" %>
    </div>
    <div class="col-sm-2"></div>
    </div>
    </div>

    <div id="chat_room", class="room_color", style="background-image: url('<%= @room.room_image %>')">
      <div class="room_color"></div>
  <!-- チャット表示部分 -->
      <div class="container">
        <div class="row">
          <div class="col-sm-2"></div>
          <div id="user_image" class="col-sm-2">
          </div>
          <div class="col-sm-6">
            <div id="chat_area">
            </div>
          </div>
          </div>
          <div class="col-sm-2"></div>
        </div>
      </div>

    </div>
  </div>

<script>
  var group_id = <%= @room.id %>;
  var dispatcher = new WebSocketRails("localhost:3000/websocket");
  var postsChannel = dispatcher.subscribe(group_id);

  // メッセージ受信時の処理
  postsChannel.bind('websocket_chat', function(message){
    var message_li = document.createElement("div");
    var image = document.createElement("img");
    var icon = image.setAttribute('src', message[3]);
    var user_nickname = document.createElement("p")
        user_nickname.textContent = message[4]
        message_li.textContent = message[0];

    document.getElementById("user_image").appendChild(image).classList.add('user_thumbnail');
    document.getElementById("user_image").appendChild(user_nickname).classList.add('user_name');
    document.getElementById("chat_area").appendChild(message_li).classList.add('balloon')
  });
 // メッセージ送信時の処理
document.getElementById("send").onclick =  function(){
  var comment = document.getElementById("comment").value;
  var nickname = '<%= @user.nickname %>';
  var user_image = '<%= @user.image %>';
  var image = document.createElement("img");
  var icon = image.setAttribute('src', user_image);
  var user_id = <%= @user.id %>
  dispatcher.trigger("websocket_chat", [comment,group_id,user_id]);
  }
</script>

app/views/users/index.html.erb
<br>
<br>
<br>





  <center><h2>らくちゃとは</h2></center>
<div class="container">
<div class="row">
<div class="col-sm-3"></div>
<div class="col-sm-6">

楽にチャットを行うことができるサービスです。面倒なユーザー登録なんかは入りません。まずは、プロフィールを選択してみましょう。
</div>
<div class="col-sm-3"></div>


  </div>
  </div>


<div class=" container profile">
<center><h2>プロフィール登録</h2></center>
 <%= form_for(@user) do |f| %>
 <center><%= f.label :nickname %></center>
 <center> <%= f.text_field :nickname, placeholder: "nickname",  autofocus: true, class: "nickname" %></center>
 <%= f.hidden_field :image %>
  <div class="col-sm-2"></div>
  <div class="col-sm-4">
      <img id="main_image">
    </div>
     <div class="col-sm-4">
      プロフィール画像をお選びください
      <br>
        <%  @images.each do |image|%>
        <%= image_tag(image.image,  class: "thumbnail") %>
        <% end %>
      <div id="thumbnails">
      </div>
      <div id="main">
      </div>
      </div>
        </div class="col-sm-2"><div>
  </div>
<div><center><%= f.submit value: "チャットへ進む" %></center></div>
  <% end %>

app/views/users/show.html.erb
<div class="top">
<div class="rooms_layout">
<% @rooms.each do |room| %>
  <% if room.user_count <= 2 %>
  <section class="item row">
  <%= link_to ({ :controller => :rooms, :action => :show, :id => room.id, :user_id => @user.id }) do %>
      <%= image_tag(room.image, class: "image") %>
      <div class="category"><%= room.name %></div>
      <p class="description">
      <% room.users.each do |user| %>
        <%= image_tag(user.image, class: "room-user-thumbnail") %>
      <% end %>
      </p>
    <% end %>
    </section>

  <% elsif room.user_count >= 3 && room.user_count <= 5 %>
  <section class="item medium middle">
  <%= link_to ({ :controller => :rooms, :action => :show, :id => room.id, :user_id => @user.id }) do %>
      <%= image_tag(room.image, class: "image") %>
      <div class="category"><%= room.name %></div>
      <p class="description">説明</p>
    <% end %>
  </section>

  <% else %>
  <section class="item large high">
  <%= link_to ({ :controller => :rooms, :action => :show, :id => room.id, :user_id => @user.id }) do %>
      <%= image_tag(room.image, class: "image") %>
      <div class="category"><%= room.name %></div>
      <p class="description">説明</p>
    <% end %>
  </section>

  <% end %>


<% end %>

</div>

  </div>

<script src="http://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.js"></script>
<script>
new Masonry('.rooms_layout', {
  itemSelector: '.item',
  columWidth: 180,
  gutter: 4
});
</script>